@base = http://meu-ambiente-express.eba-uzwuzp32.us-east-1.elasticbeanstalk.com

GET  {{base}}/health HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU4NTEyMzI4LCJleHAiOjE3NTg1MTU5Mjh9.ARX_f-ZJOuUG-RRUM3nMWHQpw2Wn9VopJl8o-FE9nLQ

